Vagrant.configure('2') do |config|
  config.vm.box = 'winbox'

  chef_type = :chef_client
  # chef_type = :chef_solo

  config.vm.provision chef_type do |chef|
    # chef.data_bags_path = 'databags'
    # chef.cookbooks_path = ['cookbooks']
    chef.add_recipe 'SC-win-run'
    # chef.json = {
    #    :sky => ['cloud']
    # }
    # chef.log_level = :debug
  end

end
